"""06 - The canonical benchmark: 1D viscous Burgers, with the recipe as command-line flags.

    u_t + u u_x = nu u_xx,   nu = 0.01/pi,   x in [-1,1],  t in (0,1]
    u(0,x) = -sin(pi x),     u(t,-1) = u(t,1) = 0

The solution develops a sharp internal layer near x=0 around t ~ 0.4 - a near-shock that
classical methods need adaptive refinement to resolve. That is why Raissi et al. chose it.
Their reported result: 9 layers x 20 units, 3021 parameters, full-batch L-BFGS,
relative L2 error 6.7e-4.

Ground truth here is generated by Cole-Hopf quadrature (pinnlab/reference.py), verified against
an independent finite-difference solve to ~5e-5. Generating your own reference beats trusting a
bundled .npz you cannot check.

THIS SCRIPT IS THE ABLATION MACHINE. Every flag is a numbered step of chapter 10:

    --hard      step 4   exact IC and BCs:  u = -sin(pi x) + t(1-x^2) N(t,x)
    --fourier   step 2   random Fourier feature embedding
    --rwf       step 3   random weight factorisation
    --causal    step 5   causal temporal weighting
    --balance   step 6   gradient-norm loss balancing
    --rar       step 8   residual-based adaptive refinement
    --lbfgs     step 7   Adam -> L-BFGS
    --plain              none of the above (the 2019 baseline)
    --all                all of the above

Run each over three seeds and build your own table. That table is the single most valuable
artifact of this whole learning path.
"""

import argparse
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

import numpy as np                                                      # noqa: E402
import torch                                                            # noqa: E402

from pinnlab import CausalWeighter, GradNormBalancer, PINN, d, set_seed, setup   # noqa: E402
from pinnlab.plotting import curves, lines, three_panel                 # noqa: E402
from pinnlab.reference import burgers_exact                             # noqa: E402
from pinnlab.sampling import latin_hypercube, rar_refine                # noqa: E402
from pinnlab.train import adam_then_lbfgs, relative_l2                  # noqa: E402

NU = 0.01 / np.pi
BOUNDS = [(0.0, 1.0), (-1.0, 1.0)]        # (t, x)


RECIPE_FLAGS = ("hard", "fourier", "rwf", "causal", "balance", "rar", "lbfgs")


def build_args():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    for flag, helptext in [
        ("hard", "exact IC/BCs by construction (step 4)"),
        ("fourier", "Fourier feature embedding (step 2)"),
        ("rwf", "random weight factorisation (step 3)"),
        ("causal", "causal temporal weighting (step 5)"),
        ("balance", "gradient-norm loss balancing (step 6)"),
        ("rar", "residual-based adaptive refinement (step 8)"),
        ("lbfgs", "polish with L-BFGS after Adam (step 7) - ON by default"),
    ]:
        ap.add_argument(f"--{flag}", action="store_true", help=helptext)
    ap.add_argument("--no-lbfgs", action="store_true", help="Adam only, no L-BFGS polish")
    ap.add_argument("--plain", action="store_true",
                    help="the 2019 baseline: soft constraints, Adam then L-BFGS, nothing else")
    ap.add_argument("--all", action="store_true", help="every recipe step ON")
    ap.add_argument("--steps", type=int, default=1000, help="Adam steps")
    ap.add_argument("--lbfgs-steps", type=int, default=2000,
                    help="L-BFGS inner iterations - this is where the accuracy comes from, and "
                         "the paper's 6.7e-4 needs several times more than the default here")
    ap.add_argument("--n-col", type=int, default=4096, help="collocation points per Adam step")
    ap.add_argument("--width", type=int, default=20, help="paper: 20 units")
    ap.add_argument("--depth", type=int, default=8, help="paper: 8 hidden layers")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--sigma", type=float, default=1.0, help="Fourier feature bandwidth")
    args = ap.parse_args()

    # Presets first, then any flag the user typed explicitly wins over the preset.
    explicit = {f for f in RECIPE_FLAGS if f"--{f}" in sys.argv}
    if args.plain:
        for k in RECIPE_FLAGS:
            setattr(args, k, k == "lbfgs")          # the paper DID use L-BFGS
    if args.all:
        for k in RECIPE_FLAGS:
            setattr(args, k, True)
    if not args.plain and not args.all:
        args.lbfgs = True                            # sensible default
    for k in explicit:
        setattr(args, k, True)
    if args.no_lbfgs:
        args.lbfgs = False
    return args


def main():
    args = build_args()
    setup()
    set_seed(args.seed)

    on = [k for k in RECIPE_FLAGS if getattr(args, k)]
    label = ", ".join(on) if on else "nothing (Adam only)"
    print(f"config: {label}   seed={args.seed}")

    def hard_fn(z, out):
        """u = -sin(pi x) + t(1-x^2) N(t,x). IC and both BCs hold identically."""
        t, x = z[:, 0:1], z[:, 1:2]
        return -torch.sin(torch.pi * x) + t * (1.0 - x ** 2) * out

    net = PINN(in_dim=2, width=args.width, depth=args.depth,
               fourier=args.fourier, fourier_features=64, sigma=args.sigma,
               rwf=args.rwf, hard=hard_fn if args.hard else None)
    print(f"network: {net.n_params()} parameters "
          f"({args.depth} hidden layers x {args.width} units, tanh)")

    state = {"pts": None, "extra": None, "ic": None, "bc": None, "frozen": False}
    causal = CausalWeighter(n_segments=32, eps=1.0, min_weight=1e-2) if args.causal else None
    n_terms = 1 if args.hard else 3
    balancer = GradNormBalancer(n_terms, net.parameters(), every=500) if args.balance else None

    def residual(z):
        u = net(z)
        g = d(u, z)
        u_t, u_x = g[:, 0:1], g[:, 1:2]
        u_xx = d(u_x, z)[:, 1:2]
        return u_t + u * u_x - NU * u_xx

    def sample():
        """Resample every Adam step (recipe step 8); freeze EVERYTHING for L-BFGS.

        Everything stochastic must be frozen, not just the interior points. A resampled IC/BC
        term is enough to make the quasi-Newton curvature estimate meaningless, and the symptom
        is L-BFGS terminating after a handful of function evaluations - watch the count it
        prints.
        """
        if state["frozen"]:
            return state["pts"], state["ic"], state["bc"]
        pts = latin_hypercube(args.n_col, BOUNDS)
        if state["extra"] is not None:
            pts = torch.cat([pts, state["extra"]], dim=0).detach().requires_grad_(True)
        x0 = torch.rand(256, 1, dtype=torch.float64) * 2 - 1
        tb = torch.rand(256, 1, dtype=torch.float64)
        return pts, x0, tb

    def loss_fn():
        z, x0, tb = sample()
        r = residual(z)
        if causal is not None:
            l_res = causal(z[:, 0:1], r, (0.0, 1.0))
        else:
            l_res = r.pow(2).mean()

        if args.hard:
            return l_res, [l_res]

        z0 = torch.cat([torch.zeros_like(x0), x0], dim=1)
        l_ic = (net(z0) + torch.sin(torch.pi * x0)).pow(2).mean()

        zb = torch.cat([torch.cat([tb, tb]),
                        torch.cat([-torch.ones_like(tb), torch.ones_like(tb)])], dim=1)
        l_bc = net(zb).pow(2).mean()

        terms = [l_res, l_ic, l_bc]
        if balancer is not None and not state["frozen"]:
            balancer.maybe_update(terms)
            return balancer.combine(terms), terms
        return l_res + l_ic + l_bc, terms

    def freeze():
        pts = latin_hypercube(10_000, BOUNDS)   # the paper's N_f, frozen for L-BFGS
        if state["extra"] is not None:
            pts = torch.cat([pts, state["extra"]], dim=0).detach().requires_grad_(True)
        state["pts"] = pts
        state["ic"] = torch.linspace(-1, 1, 256, dtype=torch.float64).reshape(-1, 1)
        state["bc"] = torch.linspace(0, 1, 256, dtype=torch.float64).reshape(-1, 1)
        state["frozen"] = True

    # fresh, dense evaluation grid - never the training points
    xs = np.linspace(-1, 1, 256)
    ts = np.linspace(0, 1, 101)
    ref = burgers_exact(xs, ts, nu=NU)
    XX, TT = np.meshgrid(xs, ts)
    z_eval = torch.tensor(np.stack([TT.ravel(), XX.ravel()], axis=1), dtype=torch.float64)
    ref_t = torch.tensor(ref.ravel(), dtype=torch.float64).reshape(-1, 1)

    def on_log(step, total, terms):
        out = {}
        with torch.no_grad():
            out["relL2"] = relative_l2(net(z_eval), ref_t)
        if args.rar and not state["frozen"] and step > 0 and step % 1000 == 0:
            new = rar_refine(lambda p: residual(p), BOUNDS, n_add=256, n_candidates=20_000)
            state["extra"] = new if state["extra"] is None else torch.cat(
                [state["extra"], new], dim=0).detach().requires_grad_(True)
            out["nRAR"] = float(state["extra"].shape[0])
        if causal is not None and causal.last_weights is not None:
            out["wLast"] = float(causal.last_weights[-1])
            out["eps"] = float(causal.last_eps)
        return out

    log = adam_then_lbfgs(net.parameters(), loss_fn, adam_steps=args.steps,
                          lbfgs_steps=args.lbfgs_steps if args.lbfgs else 0, lr=1e-3,
                          log_every=1000, on_log=on_log, freeze_for_lbfgs=freeze)

    with torch.no_grad():
        pred = net(z_eval).numpy().reshape(ref.shape)
    err = relative_l2(torch.tensor(pred), torch.tensor(ref))

    tag = "+".join(on) if on else "plain"
    three_panel(pred, ref, (-1, 1, 0, 1), f"06_burgers_{tag}_s{args.seed}.png",
                titles=("PINN", "Cole-Hopf reference", "error"))
    idx = {0.25: 25, 0.5: 50, 0.75: 75}
    lines(xs, {f"PINN t={k}": pred[v] for k, v in idx.items()} |
              {f"ref t={k}": ref[v] for k, v in idx.items()},
          f"06_burgers_slices_{tag}_s{args.seed}.png",
          title="Slices through the near-shock at x=0")
    curves({"relative L2": (log.step, [e["relL2"] for e in log.extra])},
           f"06_burgers_error_{tag}_s{args.seed}.png", ylabel="relative L2 error")

    print("\n" + "=" * 74)
    print(f"config                      : {tag}")
    print(f"relative L2 (101x256 grid)  : {err:.4e}")
    print(f"max pointwise error         : {np.abs(pred - ref).max():.4e}")
    print(f"error in the shock band     : "
          f"{np.abs(pred[:, 118:138] - ref[:, 118:138]).max():.4e}   (|x| < 0.08)")
    print(f"wall clock                  : {log.seconds:.1f} s")
    print(f"reference (Raissi et al. 2019, 3021 params, full-batch L-BFGS): 6.7e-04")
    print("=" * 74)
    print("Now change ONE flag and run again. Then change the seed and run again - PINN seed")
    print("variance is large and almost never reported.")


if __name__ == "__main__":
    main()
